### PR TITLE
support setting custom promise libs

### PR DESCRIPTION
**Pull request by vkarpov15**
Heya,

Quick suggestion - right now co uses native node promises by default and right now there's no way to change that for, say, a subclass of native node promises. We've been supporting a [similar API with mongoose](http://mongoosejs.com/docs/promises.html#plugging-in-your-own-promises-library) and it's proven to be really useful.

### CODE REVIEW

**Comment by tj** [comment]
Thanks but sorry! I don't believe this sort of thing makes sense, alternative Promise implementations are effectively polyfills, so if you reallllly want something non-native then you might as well replace the global.

cheers

**Comment by vkarpov15** [comment]
Replacing the global feels nasty though, I really don't trust every npm module I use to work correctly if I throw a custom promise lib into global, and furthermore I don't really care what promise lib something like twilio uses, but I do care about what co returns. Given that constraint, the only real alternative is to write a wrapper around co that attaches mixins to the promise, which I don't really like either.

**Comment by tj** [comment]
If people don't trust replacing the global they shouldn't use it at all IMO, Promises have a specific contract, so they either work or they don't.

**Comment by vkarpov15** [comment]
Fair point. Thanks for your comments, much appreciated :+1:

**Pull request closed without merging**
