### PR TITLE
Use '===' to compare strings.

### PR DESCRIPTION
**Pull request by ssbunny**
Use '===' instead of '==' to compare strings.

### CODE REVIEW

**Comment by madbence** [comment]
`typeof` always returns `string`, so it's safe to use `==` for comparison.

**Comment by ssbunny** [comment]
Yes, but `===` is a little bit faster.

**Comment by targos** [comment]
[It is not faster in v8](http://jsperf.com/deq-vs-teq-for-strings) but +1 for the change.  
'===' should always be used unless the flexibility of '==' is needed

**Comment by tj** [comment]
as @madbence mentioned these are always strings

**Pull request closed without merging**
