### PR TITLE
Modularity

### PR DESCRIPTION
**Pull request by hemanth**
Modularity++ ? If so we can move others as well ;)

//cc @tj

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
Why not? :+1:

**Comment by fengmk2** [comment]
keep co no deps should be better. And `thunk-to-promise` is no need to be a module.

**Comment by hemanth** [comment]
:( if at any, which are those eligible candidates?

**Comment by jonathanong** [comment]
yeah i've generally tried to avoid adding dependencies because people use this in the browser in non-commonjs environments. also, thunks shouldn't even be a thing, so i agree that `thunk-to-promise` shouldn't be a thing either :P

**Comment by hemanth** [comment]
Number of modules that can go in to this:

*  [is-promise](https://www.npmjs.com/package/is-promise)

* [is-generator-function](https://www.npmjs.com/package/is-generator-function)

* [is-generator](https://www.npmjs.com/package/is-generator)

* [isObject](https://www.npmjs.com/package/isobject)

* array-to-promise, yieldables-to-promise.

Modularity is tough to define...

**Comment by jancarloviray** [comment]
In my opinion, "co" should be simple, especially that it may be used in browsers as well. Those "helpers" are quite small. Yeah, this PR is kind of an overkill.

**Comment by hemanth** [comment]
Agree with @fengmk2 @jonathanong :smile: closing this PR.

**Pull request closed without merging**
