### PR TITLE
Has been added support for RxJs.

### PR DESCRIPTION
**Pull request by xgrommx**
I think that Observable interface is very important feature in future and I had added support for RxJs (as a popular library). Also I had added some test which was passed successfully.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
-1, you've done neat work but this should probably be published as a separate module that wraps co.

**Comment by xgrommx** [comment]
@yoshuawuyts How can I create it separately from co?

**Comment by madbence** [comment]
:-1: we should add support for observables when they become standard (see [jhusain/asyncgenerator](https://github.com/jhusain/asyncgenerator) or [zenparsing/async-iteration](https://github.com/zenparsing/async-iteration))

**Comment by fengmk2** [comment]
Agree with @madbence

**Comment by richardanaya** [comment]
This is exciting!

**Comment by tj** [comment]
Closing for now, I think we have too much stuff already, just promises would be preferred now, so if there's a rxjs-to-promise util I'd go with that

**Pull request closed without merging**
