### PR TITLE
Add UMD wrapper

### LINKED ISSUE #208: co should support for chrome
The chrome is already support for generators.

### PR DESCRIPTION
**Pull request by cesarandreu**
Closes #208.

Used [return exports](https://github.com/umdjs/umd/blob/master/returnExports.js#L40) wrapper from umdjs/umd. 

* Do you think just the UMD wrapper is fine, or should I use something like [fid-umd](https://github.com/fidian/fid-umd) or [browserify](https://github.com/substack/node-browserify) instead?

* I have no idea how to test this. Any advice?

### CODE REVIEW

**Comment by jonathanong** [comment]
yeah maybe browserify would be better so we don't touch the main code. if you wanna keep it this way, i'd rather have the UMD stuff be at the bottom of the file

**Comment by tracker1** [comment]
Personally, I think those who want to use this module in an AMD environment should use browserify as part of their own process... just my $.02 here.

**Comment by bucaran** [comment]
@tracker1 :+1:

**Comment by yoshuawuyts** [comment]
@bucaran I think it's mainly to bridge the awkward transition phase from `amd` to `commonjs`. Fwiw I agree that people should just use `browserify` instead of wrapping `co` in `umd`.

**Comment by tracker1** [comment]
@bucaran The only reason I could think of is if someone wanted to pull this module in via bower, then a UMD wrapper around it might make sense.  Though I have similar opinions on bower, and choose to "just use npm" for my modules.

**Comment by bucaran** [comment]
@tracker1 I see. What a baggage :)

**Pull request closed without merging**
