### PR TITLE
Use strict equality instead of loose equality

### PR DESCRIPTION
**Pull request by xuhong**

### CODE REVIEW

**Comment by tj** [comment]
Thanks! But == is fine here

**Comment by xuhong** [comment]
Thanks for review! I know typeof will always return a string, but there are both == and === being used when comparing with 'function' , just felling a little mess...

**Comment by tj** [comment]
ah I see, weird, it wasn't always like that haha == is fine there too

**Comment by xuhong** [comment]
giphy
well...

**Pull request closed without merging**
